name         'puppetlabs-heat'
version      '4.0.0'
author       'eNovance and StackForge Contributors'
license      'Apache License 2.0'
summary      'Puppet module for OpenStack Heat'
description  'Installs and configures OpenStack Heat (Orchestration).'
project_page 'https://launchpad.net/puppet-heat'
source       'https://github.com/stackforge/puppet-heat'

dependency 'puppetlabs/inifile', '>= 1.0.0 <2.0.0'
dependency 'puppetlabs/keystone', '>=4.0.0 <5.0.0'
dependency 'puppetlabs/stdlib', '>= 4.0.0 < 5.0.0'
dependency 'stackforge/openstacklib', '>=5.0.0'
