name         'puppetlabs-heat'
version      '4.0.0'
author       'eNovance and StackForge Contributors'
license      'Apache License 2.0'
summary      'Puppet module for OpenStack Heat'
description  'Installs and configures OpenStack Heat (Orchestration).'
project_page 'https://launchpad.net/puppet-heat'
source       'https://github.com/stackforge/puppet-heat'

dependency 'puppetlabs/inifile', '>= 1.0.0 <2.0.0'
dependency 'puppetlabs/mysql', '>=0.9.0 <3.0.0'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
